package com.sekwah.narutomod.block;

import com.sekwah.narutomod.block.weapons.PaperBombBlock;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import static com.sekwah.narutomod.NarutoMod.MOD_ID;

public class NarutoBlocks {

    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, MOD_ID);
    public static final DeferredRegister<Item> BLOCK_ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MOD_ID);

    // TODO find a way to apply these to the paper bomb
    //public static final Material UNSTABLE_EXPLOSIVE = (new Material.Builder(MaterialColor.FIRE)).noCollider().flammable().notSolidBlocking().nonSolid().destroyOnPush().build();

    public static final RegistryObject<Block> PAPER_BOMB = BLOCKS.register("paper_bomb",
            () -> {
                BlockBehaviour.Properties blockBehavior = BlockBehaviour.Properties.of()
                        .noCollission()
                        .instabreak()
                        .strength(0.5F)
                        .sound(SoundType.CROP);
        return new PaperBombBlock(blockBehavior);
            });

    public static final RegistryObject<Item> ITEM_PAPER_BOMB = BLOCK_ITEMS.register("paper_bomb", ()
            -> new BlockItem(PAPER_BOMB.get(), new Item.Properties()));

    public static final RegistryObject<Block> BONSAI_TREE = BLOCKS.register("bonsai_tree",
            () -> new RotatableDecorativeBlock(BlockBehaviour.Properties.of().strength(0.5F).sound(SoundType.CROP)
                    , Block.box(2.0D, 0.0D, 2.0D, 14.0D, 8.0D, 14.0D)));

    public static final RegistryObject<Item> ITEM_BONSAI_TREE = BLOCK_ITEMS.register("bonsai_tree", ()
            -> new BlockItem(BONSAI_TREE.get(), new Item.Properties()));

    /**
     * The pale slabs that float in Kamui's dimension. Indestructible on purpose - the
     * platform under your feet in a bottomless void is not something a stray pickaxe or
     * a creeper should be able to remove.
     *
     * Registered with no BlockItem: it is scenery generated by the jutsu, not a material.
     */
    /**
     * The black flame itself. Unbreakable so it cannot simply be punched out, no collision
     * so you walk into it, and lit dimly rather than brightly - Amaterasu is black fire and
     * should darken a room, not light it.
     */
    public static final RegistryObject<Block> AMATERASU_FLAME = BLOCKS.register("amaterasu_flame",
            () -> new AmaterasuFlameBlock(BlockBehaviour.Properties.of()
                    .noCollission()
                    .strength(-1.0F, 3600000.0F)
                    .lightLevel(state -> 2)
                    .sound(SoundType.WOOL)
                    .noLootTable()
                    .replaceable()
                    .pushReaction(net.minecraft.world.level.material.PushReaction.DESTROY)));

    public static final RegistryObject<Block> KAMUI_BLOCK = BLOCKS.register("kamui_block",
            () -> new Block(BlockBehaviour.Properties.of()
                    .strength(-1.0F, 3600000.0F)   // unbreakable, blast-proof (bedrock's values)
                    .sound(SoundType.STONE)
                    .lightLevel(state -> 3)        // faintly lit, so the void reads as lit by them
                    .noLootTable()
                    .isValidSpawn((state, level, pos, type) -> false)));

    public static void register(IEventBus eventBus) {
        BLOCKS.register(eventBus);
        BLOCK_ITEMS.register(eventBus);
    }
}
